      - name: Build with Buildozer
        uses: artemsbulgakov/buildozer-action@v1
        env:
          USER: root
          PIP_BREAK_SYSTEM_PACKAGES: 1
          BUILDOZER_ALLOW_ORG_TEST_DOMAIN: 1
          BUILDOZER_WARN_ON_ROOT: 0
        with:
          # This 'yes y |' part is the secret to fixing the root error
          command: yes y | buildozer android debug
          workdir: .
          buildozer_version: master
